const { renderTemplate } = foundry.applications.handlebars;

const maxStatValue = 7;

/**
 * Extend the base Actor document with the functionality we need for tracking stats
 * @extends {Actor}
 */
export class DefWizActor extends Actor {

  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    const actorData = this;
    const flags = actorData.flags.definitelywizards || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  async updateStat(statType, offset) {
    var oldValue = 0;
    var newValue = 0;
    var localizedChatLabel = "";
    var updateData = {};

    switch (statType) {
      case "wizard":
        oldValue = this.system.stats.wizard.value;
        newValue = oldValue + offset;
        localizedChatLabel = game.i18n.localize("DW.Wizard");
        updateData = {"system.stats.wizard.value": newValue};
        break;
      case "wild":
        oldValue = this.system.stats.wild.value;
        newValue = oldValue + offset;
        localizedChatLabel = game.i18n.localize("DW.Wild");
        updateData = {"system.stats.wild.value": newValue};
        break;
      default:
        return;
    }

    if (newValue <= maxStatValue && newValue > 0) {
      await this.update(updateData);
      await this._postUpdateToChat(localizedChatLabel, oldValue, newValue);
    }
  }

  async resetStat(statType) {
    switch (statType) {
      case "wizard":
        const wizardStat = this.system.stats.wizard.value;
        const newWizardValue = 2;
        await this.update({ "system.stats.wizard.value": newWizardValue });
        await this._postUpdateToChat(game.i18n.localize("DW.Wizard"), wizardStat, newWizardValue);
        break;
      case "wild":
        const wildStat = this.system.stats.wild.value;
        const newWildValue = 2;
        await this.update({ "system.stats.wild.value": newWildValue });
        await this._postUpdateToChat(game.i18n.localize("DW.Wild"), wildStat, newWildValue);
        break;
      default:
        break;
    }
  }

  async _postUpdateToChat(statType, oldValue, newValue) {
        const template = "systems/def-wiz-2/templates/chat/actor-stat-update.hbs";

        let templateData = {
            statType: statType,
            oldValue: oldValue,
            newValue: newValue,
            owner: this.id
        };

        ChatMessage.create({
            user: game.user.id,
            speaker: ChatMessage.getSpeaker({actor: this}),
            content: await renderTemplate(template, templateData),
            style: CONST.CHAT_MESSAGE_STYLES.OOC
        });
    }
}
